openapi: "3.0.0"
info:
  version: 1.0.0
  title: Example
paths:
  /things:
    get:
      security:
        - RoleAuth:
            - "normal"
      responses:
        200:
          description: a list of things
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ThingWithID'
  /admin/things:
    get:
      security:
        - RoleAuth:
            - "admin"
      responses:
        200:
          description: a list of things
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ThingWithID'
components:
  schemas:
    Thing:
      properties:
        name:
          type: string
      required:
        - name
    ThingWithID:
      allOf:
        - $ref: '#/components/schemas/Thing'
        - properties:
            id:
              type: integer
              format: int64
          required:
            - id
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
  securitySchemes:
    RoleAuth:
      type: http
      scheme: bearer
